### ISSUE TITLE
Fix EOLError from multiprocessing when running on windows without cygwin

### ISSUE THREAD

**Issue by kulverstukas1** [EvilzoneLabs/BeastBot#6]
Fix EOLError from multiprocessing when running on windows without cygwin.

**Comment by kenjoe41** [comment]
This is raised from the recv() function when nothing is there to receive and the other end closed th socket. That is from `https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Connection.recv` and i think a simple try..except would do which could be in just there or you write an abstraction over recv() and put the try..except  in your statement. Try it and see if it works.

**Comment by kulverstukas1** [comment]
Stacktrace:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError

Error log:
CRITICAL - 21:17:59 - Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x01926EF0>: it's not found as **main**.recvfrom_into - Filename: BeastBot.py - Line Number:  85 - Function:  main - Line Text:  functionProc.start())

**Comment by kenjoe41** [comment]
`https://docs.python.org/2/library/multiprocessing.html#windows` 
`http://stackoverflow.com/a/9671030/4671205`
Damn, those restrictions. Should find a way to bypass them. My windows install isn't perfect yet to test out but try removing the except catching all errors and we see which error type it throws and which function it complains about.

**Comment by chris2727** [comment]
I personally will not be working on this. If this is something kenjoe, kulver or someone else wishes to work on, then I would still be greatful. I will keep this issue open just for awarness. :)
